In [1]:
import numpy

In [2]:
e1 = numpy.array([[1],[0],[0]])
print(e1)

[[1]
 [0]
 [0]]


In [3]:
x = numpy.array([[1],[2],[2]])
print(x)

[[1]
 [2]
 [2]]


In [4]:
c1 = x[0,0]/(x[0,0]**2+x[1,0]**2)**0.5
s1 = x[1,0]/(x[0,0]**2+x[1,0]**2)**0.5
T12 = numpy.array([[c1, s1 , 0],[-s1, c1, 0],[0, 0, 1]])
print("T12")
print(T12)

T12
[[ 0.4472136   0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]


In [5]:
T12x = numpy.dot(T12,x) 
print(T12x)

[[2.23606798]
 [0.        ]
 [2.        ]]


In [6]:
c2 = (x[0,0]**2+x[1,0]**2)**0.5/(x[0,0]**2+x[1,0]**2+x[2,0]**2)**0.5
s2 = x[2,0]/(x[0,0]**2+x[1,0]**2+x[2,0]**2)**0.5
T13 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2]])
print("T13")
print(T13)

T13
[[ 0.74535599  0.          0.66666667]
 [ 0.          1.          0.        ]
 [-0.66666667  0.          0.74535599]]


In [7]:
T13x = numpy.dot(T13,T12x) 
print(T13x)

[[3.]
 [0.]
 [0.]]


In [8]:
T = numpy.dot(T13,T12)
print(T)

[[ 0.33333333  0.66666667  0.66666667]
 [-0.89442719  0.4472136   0.        ]
 [-0.2981424  -0.59628479  0.74535599]]


In [9]:
a = numpy.dot(T,x)/e1
print(a)


[[ 3.]
 [nan]
 [inf]]


C:\Users\WYY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\WYY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
