In [1]:
import numpy

In [2]:
#输入一个矩阵(3阶)
A = numpy.array([[2, 2 , 1],[0, 2, 2],[2, 1, 2]])
print(A)

[[2 2 1]
 [0 2 2]
 [2 1 2]]


In [3]:
b1 = numpy.array([A[0,0],A[1,0],A[2,0]])
print(b1)

[2 0 2]


In [4]:
if A[0,0] != 0 or A[1,0] != 0 : 
    c1 = A[0,0]/(A[0,0]**2+A[1,0]**2)**0.5
    s1 = A[1,0]/(A[0,0]**2+A[1,0]**2)**0.5
    T121 = numpy.array([[c1, s1 , 0],[-s1, c1, 0],[0, 0, 1]])
    print("T121")
    print(T121)
    
    c2 = (A[0,0]**2+A[1,0]**2)**0.5/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    s2 = A[2,0]/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    T131 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2]])
    print("T131")
    print(T131)
    
    
elif (A[0,0]**2+A[1,0]**2)**0.5 != 0 or A[2,0] != 0 :
    c2 = (A[0,0]**2+A[1,0]**2)**0.5/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    s2 = A[2,0]/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    T131 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2]])
    print("T131")
    print(T131)
    

T121
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
T131
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


In [5]:
if A[0,0] != 0 or A[1,0] != 0 : 
    
    print("T121 b1")
    print(numpy.dot(T121 ,b1))
    print("T131(T121 b1)")
    print(numpy.dot(T131,numpy.dot(T121,b1)))    
    T1 = numpy.dot(T121,T131)      
    print("T1")    
    print(T1)
    
    
elif(A[0,0]**2+A[1,0]**2)**0.5 != 0 or A[2,0] != 0 :
   
    T1 = T131
    print("T1")    
    print(T1)
    print("T131(T121 b1)")
    print(numpy.dot(T1,b1))
    

T121 b1
[2. 0. 2.]
T131(T121 b1)
[2.82842712 0.         0.        ]
T1
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


In [6]:
M = numpy.dot(T1 ,A)
print("T1 A")
print(M)
print("A1")
A1 = numpy.array([[M[1,1],M[1,2]],[M[2,1],M[2,2]]])
print(A1)

T1 A
[[ 2.82842712  2.12132034  2.12132034]
 [ 0.          2.          2.        ]
 [ 0.         -0.70710678  0.70710678]]
A1
[[ 2.          2.        ]
 [-0.70710678  0.70710678]]


In [7]:
b2 = numpy.array([[A1[0,0]],[A1[1,0]]])
print(b2)

[[ 2.        ]
 [-0.70710678]]


In [8]:
if A1[0,0] != 0 or A1[1,0] != 0 : 
    c1 = A1[0,0]/(A1[0,0]**2+A1[1,0]**2)**0.5
    s1 = A1[1,0]/(A1[0,0]**2+A1[1,0]**2)**0.5
    T122 = numpy.array([[c1, s1],[-s1, c1]])
    print("T122")
    print(T122)

    T122b2 = numpy.dot(T122 ,b2)
    print("T122b2")
    print(T122b2)
    
    T2 = T122
    print("T2")
    print(T2)

T122
[[ 0.94280904 -0.33333333]
 [ 0.33333333  0.94280904]]
T122b2
[[2.12132034]
 [0.        ]]
T2
[[ 0.94280904 -0.33333333]
 [ 0.33333333  0.94280904]]


In [9]:
N = numpy.dot(T2 ,A1)
print("T2 A1")
print(N)

T2 A1
[[2.12132034 1.64991582]
 [0.         1.33333333]]


In [10]:
T = numpy.dot([[1, 0, 0],[0,T2[0,0],T2[0,1]],[0,T2[1,0],T2[1,1]]],T1)
print(T)

[[ 0.70710678  0.          0.70710678]
 [ 0.23570226  0.94280904 -0.23570226]
 [-0.66666667  0.33333333  0.66666667]]


In [11]:
Q = T.T
print(Q)

[[ 0.70710678  0.23570226 -0.66666667]
 [ 0.          0.94280904  0.33333333]
 [ 0.70710678 -0.23570226  0.66666667]]


In [12]:
R = numpy.array([[M[0,0],M[0,1],M[0,2]],[0, N[0,0],N[0,1]],[0, N[1,0],N[1,1]]])
print(R)

[[2.82842712 2.12132034 2.12132034]
 [0.         2.12132034 1.64991582]
 [0.         0.         1.33333333]]


In [13]:
A = numpy.dot(Q,R)
print(A)

[[2. 2. 1.]
 [0. 2. 2.]
 [2. 1. 2.]]
