In [1]:
import numpy

In [2]:
#输入一个矩阵(4阶)
A = numpy.array([[0,3 , 1, -4],[0, 4, -2, 3],[2, 1, 2, 4],[0, 0, 0, -5]])
print(A)

[[ 0  3  1 -4]
 [ 0  4 -2  3]
 [ 2  1  2  4]
 [ 0  0  0 -5]]


In [3]:
b1 = numpy.array([A[0,0],A[1,0],A[2,0],A[3,0]])
print(b1)

[0 0 2 0]


In [4]:
if A[0,0] != 0 or A[1,0] != 0 : 
    c1 = A[0,0]/(A[0,0]**2+A[1,0]**2)**0.5
    s1 = A[1,0]/(A[0,0]**2+A[1,0]**2)**0.5
    T121 = numpy.array([[c1, s1 , 0, 0],[-s1, c1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
    print("T12")
    print(T12)
    
    c2 = (A[0,0]**2+A[1,0]**2)**0.5/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    s2 = A[2,0]/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    T131 = numpy.array([[c2, 0 , s2, 0],[0, 1, 0, 0],[-s2, 0, c2, 0],[0, 0, 0, 1]])
    print("T13")
    print(T13)
    
    
elif (A[0,0]**2+A[1,0]**2)**0.5 != 0 or A[2,0] != 0 :
    c2 = (A[0,0]**2+A[1,0]**2)**0.5/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    s2 = A[2,0]/(A[0,0]**2+A[1,0]**2+A[2,0]**2)**0.5
    T131 = numpy.array([[c2, 0 , s2, 0],[0, 1, 0, 0],[-s2, 0, c2, 0],[0, 0, 0, 1]])
    print("T131")
    print(T131)

T131
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]


In [5]:
if A[0,0] != 0 or A[1,0] != 0 : 
    
    print("T121 b1")
    print(numpy.dot(T12 ,b1))
    print("T131(T12 b1)")
    print(numpy.dot(T131,numpy.dot(T121,b1)))    
    T1 = numpy.dot(T121,T131)      
    print("T1")    
    print(T1)
    
    
elif(A[0,0]**2+A[1,0]**2)**0.5 != 0 or A[2,0] != 0 :
   
    T1 = T131
    print("T1")    
    print(T1)
    print("T131(T121 b1)")
    print(numpy.dot(T1,b1))
    

T1
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
T131(T121 b1)
[2. 0. 0. 0.]


In [6]:
M = numpy.dot(T1 ,A)
print("T1 A")
print(M)
print("A1")
A1 = numpy.array([[M[1,1],M[1,2],M[1,3]],[M[2,1],M[2,2],M[2,3]],[M[3,1],M[3,2],M[3,3]]])
print(A1)

T1 A
[[ 2.  1.  2.  4.]
 [ 0.  4. -2.  3.]
 [ 0. -3. -1.  4.]
 [ 0.  0.  0. -5.]]
A1
[[ 4. -2.  3.]
 [-3. -1.  4.]
 [ 0.  0. -5.]]


In [7]:
b2 = numpy.array([[A1[0,0]],[A1[1,0]],[A1[2,0]]])
print(b2)

[[ 4.]
 [-3.]
 [ 0.]]


In [8]:
if A1[0,0] != 0 or A1[1,0] != 0 : 
    c1 = A1[0,0]/(A1[0,0]**2+A1[1,0]**2)**0.5
    s1 = A1[1,0]/(A1[0,0]**2+A1[1,0]**2)**0.5
    T122 = numpy.array([[c1, s1 , 0],[-s1, c1, 0],[0, 0, 1]])
    print("T122")
    print(T122)

    T122b2 = numpy.dot(T122 ,b2)
    print("T122b2")
    print(T122b2)
    if T122b2[1,0]<10e-6 and T122b2[2,0]<10e-6:
        T2 = T122
        print("T122")
        print(T122)
    else:
        c2 = (A1[0,0]**2+A1[1,0]**2)**0.5/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
        s2 = A1[2,0]/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
        T132 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2]])
        print("T132")
        print(T132)
    
elif (A1[0,0]**2+A1[1,0]**2)**0.5 != 0 or A1[2,0] != 0 :
    c2 = (A1[0,0]**2+A1[1,0]**2)**0.5/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
    s2 = A1[2,0]/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
    T132 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2],])
    print("T132")
    print(T132)

T122
[[ 0.8 -0.6  0. ]
 [ 0.6  0.8  0. ]
 [ 0.   0.   1. ]]
T122b2
[[ 5.0000000e+00]
 [-4.4408921e-16]
 [ 0.0000000e+00]]
T122
[[ 0.8 -0.6  0. ]
 [ 0.6  0.8  0. ]
 [ 0.   0.   1. ]]


In [9]:
if A1[0,0] != 0 or A1[1,0] != 0 : 
    T122b2 = numpy.dot(T122 ,b2)
    print("T122b2")
    print(numpy.dot(T122 ,b2))
    
    if T122b2[1,0]<10e-6 and T122b2[2,0]<10e-6:
        T2 = T122
        print("T2")
        print(T122)
    else:
        c2 = (A1[0,0]**2+A1[1,0]**2)**0.5/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
        s2 = A1[2,0]/(A1[0,0]**2+A1[1,0]**2+A1[2,0]**2)**0.5
        T132 = numpy.array([[c2, 0 , s2],[0, 1, 0],[-s2, 0, c2]])
        print("T132")
        print(T132)
        T2 = numpy.dot(T122,T132)
        print("T2")    
        print(T2)
    
elif(A1[0,0]**2+A1[1,0]**2)**0.5 != 0 or A1[2,0] != 0 :
    T2 = T122
    print("T2")    
    print(T2)
    
    
    

T122b2
[[ 5.0000000e+00]
 [-4.4408921e-16]
 [ 0.0000000e+00]]
T2
[[ 0.8 -0.6  0. ]
 [ 0.6  0.8  0. ]
 [ 0.   0.   1. ]]


In [10]:
N = numpy.dot(T2 ,A1)
print("T2 A1")
print(N)

T2 A1
[[ 5.0000000e+00 -1.0000000e+00  4.4408921e-16]
 [-4.4408921e-16 -2.0000000e+00  5.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -5.0000000e+00]]


In [11]:
T = numpy.dot([[1, 0, 0, 0],[0,T2[0,0],T2[0,1],T2[0,2]],[0,T2[1,0],T2[1,1],T2[1,2]],[0,T2[2,0],T2[2,1],T2[2,2]]],T1)
print(T)

[[ 0.   0.   1.   0. ]
 [ 0.6  0.8  0.   0. ]
 [-0.8  0.6  0.   0. ]
 [ 0.   0.   0.   1. ]]


In [12]:
Q = T.T
print(Q)

[[ 0.   0.6 -0.8  0. ]
 [ 0.   0.8  0.6  0. ]
 [ 1.   0.   0.   0. ]
 [ 0.   0.   0.   1. ]]


In [13]:
R = numpy.array([[M[0,0],M[0,1],M[0,2],M[0,3]],[0, N[0,0],N[0,1],N[0,2]],[0, N[1,0],N[1,1],N[1,2]],[0, N[2,0],N[2,1],N[2,2]]])
print(R)

[[ 2.0000000e+00  1.0000000e+00  2.0000000e+00  4.0000000e+00]
 [ 0.0000000e+00  5.0000000e+00 -1.0000000e+00  4.4408921e-16]
 [ 0.0000000e+00 -4.4408921e-16 -2.0000000e+00  5.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 -5.0000000e+00]]


In [14]:
A = numpy.dot(Q,R)
print(A)

[[ 0.  3.  1. -4.]
 [ 0.  4. -2.  3.]
 [ 2.  1.  2.  4.]
 [ 0.  0.  0. -5.]]
