In [2]:
import numpy

In [3]:
e1 = numpy.array([[1],[0],[0],[0]])
print(e1)

[[1]
 [0]
 [0]
 [0]]


In [4]:
x = numpy.array([[2],[3],[0],[5]])
print(x)

[[2]
 [3]
 [0]
 [5]]


In [5]:
c1 = x[0,0]/(x[0,0]**2+x[1,0]**2)**0.5
s1 = x[1,0]/(x[0,0]**2+x[1,0]**2)**0.5
T12 = numpy.array([[c1, s1 , 0, 0],[-s1, c1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])
print("T12")
print(T12)

T12
[[ 0.5547002   0.83205029  0.          0.        ]
 [-0.83205029  0.5547002   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [6]:
T12x = numpy.dot(T12,x) 
print(T12x)

[[3.60555128]
 [0.        ]
 [0.        ]
 [5.        ]]


In [7]:
c2 = (x[0,0]**2+x[1,0]**2)**0.5/(x[0,0]**2+x[1,0]**2+x[2,0]**2)**0.5
s2 = x[2,0]/(x[0,0]**2+x[1,0]**2+x[2,0]**2)**0.5
T13 = numpy.array([[c2, 0 , s2, 0],[0, 1, 0, 0],[-s2, 0, c2, 0],[0, 0, 0, 1]])
print("T13")
print(T13)

T13
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [8]:
T13x = numpy.dot(T13,T12x) 
print(T13x)

[[3.60555128]
 [0.        ]
 [0.        ]
 [5.        ]]


In [9]:
c3 = (x[0,0]**2+x[1,0]**2+x[2,0]**2)**0.5/(x[0,0]**2+x[1,0]**2+x[2,0]**2+x[3,0]**2)**0.5
s3 = x[3,0]/(x[0,0]**2+x[1,0]**2+x[2,0]**2+x[3,0]**2)**0.5
T14 = numpy.array([[c3, 0 , 0, s3],[0, 1, 0, 0],[0, 0, 1, 0],[-s3, 0, 0, c3]])
print("T14")
print(T14)

T14
[[ 0.58489765  0.          0.          0.81110711]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.81110711  0.          0.          0.58489765]]


In [10]:
T14x = numpy.dot(T14,T13x) 
print(T14x)

[[ 6.1644140e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [-4.4408921e-16]]


In [17]:
T = numpy.dot(T14,numpy.dot(T13,T12))
print("T14 T13:")
print(numpy.dot(T14,T13))
print("T:")
print(T)

T14 T13:
[[ 0.58489765  0.          0.          0.81110711]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.81110711  0.          0.          0.58489765]]
T:
[[ 0.32444284  0.48666426  0.          0.81110711]
 [-0.83205029  0.5547002   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.44992127 -0.67488191  0.          0.58489765]]


In [14]:
a = numpy.dot(T,x)/e1
print(a)

[[6.164414]
 [     nan]
 [     nan]
 [    -inf]]


C:\Users\WYY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\WYY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
