In [1]:
import numpy

In [2]:
e3 = numpy.array([[1],[0],[0]])
print(e3)

[[1]
 [0]
 [0]]


In [3]:
e2 = numpy.array([[1],[0]])
print(e2)

[[1]
 [0]]


In [4]:
I3 = numpy.array([[1, 0 , 0],[0, 1, 0],[0, 0, 1]])
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
I2 = numpy.array([[1, 0 ],[0, 1]])
print(I2)

[[1 0]
 [0 1]]


In [6]:
#输入一个矩阵(3阶)
A = numpy.array([[0, 3 , 1],[0, 4, -2],[2, 1, 2]])
print(A)

[[ 0  3  1]
 [ 0  4 -2]
 [ 2  1  2]]


In [7]:
#(1)对矩阵A第一列构造Householder矩阵
b1 = numpy.array([[A[0,0]],[A[1,0]],[A[2,0]]])
b1m = numpy.sqrt((b1**2).sum())
print("b1m")
print(b1m)
print("b1")
print(b1)

b1m
2.0
b1
[[0]
 [0]
 [2]]


In [8]:
a1 = b1 - b1m*e3
print(a1)
a1m = numpy.sqrt((a1**2).sum())

u1 = numpy.array([[a1[0,0]/a1m],[a1[1,0]/a1m],[a1[2,0]/a1m]])
print("u1")
print(u1)

[[-2.]
 [ 0.]
 [ 2.]]
u1
[[-0.70710678]
 [ 0.        ]
 [ 0.70710678]]


In [9]:
H1 = I3 - 2*numpy.dot(u1,u1.T)
print(H1)

[[2.22044605e-16 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 0.00000000e+00 2.22044605e-16]]


In [10]:
print("H1 A")
print(numpy.dot(H1,A))

H1 A
[[ 2.0000000e+00  1.0000000e+00  2.0000000e+00]
 [ 0.0000000e+00  4.0000000e+00 -2.0000000e+00]
 [ 4.4408921e-16  3.0000000e+00  1.0000000e+00]]


In [11]:
#(2)对矩阵A1第一列构造Householder矩阵
M = numpy.dot(H1,A)
A1 = numpy.array([[M[1,1],M[1,2]],[M[2,1],M[2,2]]])
print("A1")
print(A1)

b2 = numpy.array([[A1[0,0]],[A1[1,0]]])
b2m = numpy.sqrt((b2**2).sum())
print("b2m")
print(b2m)
print("b2")
print(b2)

A1
[[ 4. -2.]
 [ 3.  1.]]
b2m
4.999999999999999
b2
[[4.]
 [3.]]


In [12]:
a2 = b2 - b2m*e2
print(a2)
a2m = numpy.sqrt((a2**2).sum())

u2 = numpy.array([[a2[0,0]/a2m],[a2[1,0]/a2m]])
print("u2")
print(u2)

[[-1.]
 [ 3.]]
u2
[[-0.31622777]
 [ 0.9486833 ]]


In [13]:
H2 = I2 - 2*numpy.dot(u2,u2.T)
print(H2)

[[ 0.8  0.6]
 [ 0.6 -0.8]]


In [14]:
print("H2 A1")
N = numpy.dot(H2,A1) 
print(N)

H2 A1
[[ 5.0000000e+00 -1.0000000e+00]
 [-8.8817842e-16 -2.0000000e+00]]


In [15]:
S = numpy.dot([[1, 0, 0],[0,H2[0,0],H2[0,1]],[0,H2[1,0],H2[1,1]]],H1)
print(S)

[[ 2.22044605e-16  0.00000000e+00  1.00000000e+00]
 [ 6.00000000e-01  8.00000000e-01  1.33226763e-16]
 [-8.00000000e-01  6.00000000e-01 -1.77635684e-16]]


In [16]:
Q = S.T
print(Q)

[[ 2.22044605e-16  6.00000000e-01 -8.00000000e-01]
 [ 0.00000000e+00  8.00000000e-01  6.00000000e-01]
 [ 1.00000000e+00  1.33226763e-16 -1.77635684e-16]]


In [17]:
R = numpy.array([[M[0,0],M[0,1],M[0,2]],[0, N[0,0],N[0,1]],[0, N[1,0],N[1,1]]])
print(R)

[[ 2.0000000e+00  1.0000000e+00  2.0000000e+00]
 [ 0.0000000e+00  5.0000000e+00 -1.0000000e+00]
 [ 0.0000000e+00 -8.8817842e-16 -2.0000000e+00]]


In [18]:
A = numpy.dot(Q,R)
print(A)

[[ 4.4408921e-16  3.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00  4.0000000e+00 -2.0000000e+00]
 [ 2.0000000e+00  1.0000000e+00  2.0000000e+00]]
