In [1]:
import numpy

In [2]:
#输入一个矩阵(3阶)
A = numpy.array([[2, -1 , 3],[1, 2, 1],[2, 4, 3]])
print(A)

[[ 2 -1  3]
 [ 1  2  1]
 [ 2  4  3]]


In [3]:
b = numpy.array([[-3], [4] , [7]])
print(b)

[[-3]
 [ 4]
 [ 7]]


In [4]:
#构造矩阵L1
L1 = numpy.array([[1, 0 , 0],[A[1,0]/A[0,0], 1, 0],[A[2,0]/A[0,0], 0, 1]])
print("L1:")
print(L1)
L1_ = numpy.array([[1, 0 , 0],[A[1,0]/-A[0,0], 1, 0],[A[2,0]/-A[0,0], 0, 1]])
print("L1_:")
print(L1_)

L1:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  0.  1. ]]
L1_:
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [-1.   0.   1. ]]


In [5]:
A1 = numpy.dot(L1_, A)
print("A1")
print(A1)

A1
[[ 2.  -1.   3. ]
 [ 0.   2.5 -0.5]
 [ 0.   5.   0. ]]


In [6]:
#构造矩阵L2
L2 = numpy.array([[1, 0 , 0],[0, 1, 0],[0, A1[2,1]/A1[1,1], 1]])
print("L2:")
print(L2)
L2_ = numpy.array([[1, 0 , 0],[0, 1, 0],[0, -A1[2,1]/A1[1,1], 1]])
print("L2_:")
print(L2_)

L2:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
L2_:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]]


In [7]:
U = numpy.dot(L2_, A1)
print("U")
print(U)

U
[[ 2.  -1.   3. ]
 [ 0.   2.5 -0.5]
 [ 0.   0.   1. ]]


In [8]:
L = numpy.dot(L1, L2)
print("L")
print(L)

L
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  2.  1. ]]


In [9]:
A = numpy.dot(L,U)
print(A)

[[ 2. -1.  3.]
 [ 1.  2.  1.]
 [ 2.  4.  3.]]


In [10]:
L_ = numpy.linalg.inv(L)
print(L_)
print(numpy.dot(L_, L))
y = numpy.dot(L_, b)
print(y)

[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [-0.  -2.   1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-3. ]
 [ 5.5]
 [-1. ]]


In [11]:
U_ = numpy.linalg.inv(U)
print(U_)
print(numpy.dot(U_, U))
x = numpy.dot(U_, y)
print(x)

[[ 0.5  0.2 -1.4]
 [ 0.   0.4  0.2]
 [ 0.   0.   1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.]
 [ 2.]
 [-1.]]


In [12]:
print(numpy.dot(L,y))

[[-3.]
 [ 4.]
 [ 7.]]


In [13]:
print(numpy.dot(U,x))

[[-3. ]
 [ 5.5]
 [-1. ]]


In [14]:
print(numpy.dot(A,x))

[[-3.]
 [ 4.]
 [ 7.]]
