In [1]:
import numpy

In [2]:
#输入一个矩阵(3阶)
A = numpy.array([[3, 14, 9],[6, 43, 3],[6, 22, 15]])
print(A)

[[ 3 14  9]
 [ 6 43  3]
 [ 6 22 15]]


In [12]:
b = numpy.array([[26], [-23] , [55]])
print(b)

[[ 26]
 [-23]
 [ 55]]


In [3]:
a1 = numpy.array([[A[0,0]],[A[1,0]],[A[2,0]]])
print("a1")
print(a1)

a2 = numpy.array([[A[0,1]],[A[1,1]],[A[2,1]]])
print("a2")
print(a2)

a3 = numpy.array([[A[0,2]],[A[1,2]],[A[2,2]]])
print("a3")
print(a3)

a1
[[3]
 [6]
 [6]]
a2
[[14]
 [43]
 [22]]
a3
[[ 9]
 [ 3]
 [15]]


In [4]:
#正交化
b1 = a1
print("b1:")
print(b1)

k21 = (a2[0,0]*b1[0,0]+a2[1,0]*b1[1,0]+a2[2,0]*b1[2,0])/(b1[0,0]*b1[0,0]+b1[1,0]*b1[1,0]+b1[2,0]*b1[2,0])
print("k21:")
print(k21)
b2 = a2 - k21*b1
print("b2:")
print(b2)

k32 = (a3[0,0]*b2[0,0]+a3[1,0]*b2[1,0]+a3[2,0]*b2[2,0])/(b2[0,0]*b2[0,0]+b2[1,0]*b2[1,0]+b2[2,0]*b2[2,0])
print("k32:")
print(k32)
k31 = (a3[0,0]*b1[0,0]+a3[1,0]*b1[1,0]+a3[2,0]*b1[2,0])/(b1[0,0]*b1[0,0]+b1[1,0]*b1[1,0]+b1[2,0]*b1[2,0])
print("k31:")
print(k31)
b3 = a3 - k32*b2 - k31*b1
print("b3:")
print(b3)


b1:
[[3]
 [6]
 [6]]
k21:
5.333333333333333
b2:
[[ -2.]
 [ 11.]
 [-10.]]
k32:
-0.6
k31:
1.6666666666666667
b3:
[[ 2.8]
 [-0.4]
 [-1. ]]


In [5]:
b1m = numpy.sqrt((b1**2).sum())
q1 = numpy.array([[b1[0,0]/b1m],[b1[1,0]/b1m],[b1[2,0]/b1m]])
print("q1")
print(q1)

b2m = numpy.sqrt((b2**2).sum())
q2 = numpy.array([[b2[0,0]/b2m],[b2[1,0]/b2m],[b2[2,0]/b2m]])
print("q2")
print(q2)

b3m = numpy.sqrt((b3**2).sum())
q3= numpy.array([[b3[0,0]/b3m],[b3[1,0]/b2m],[b3[2,0]/b3m]])
print("q3")
print(q3)


q1
[[0.33333333]
 [0.66666667]
 [0.66666667]]
q2
[[-0.13333333]
 [ 0.73333333]
 [-0.66666667]]
q3
[[ 0.93333333]
 [-0.02666667]
 [-0.33333333]]


In [6]:
C = numpy.array([[1, k21, k31],[0, 1, k32],[0, 0, 1]])
print("C:")
print(C)

C:
[[ 1.          5.33333333  1.66666667]
 [ 0.          1.         -0.6       ]
 [ 0.          0.          1.        ]]


In [7]:
D = numpy.array([[b1m, 0, 0],[0, b2m, 0],[0, 0, b3m]])
print("D:")
print(D)

D:
[[ 9.  0.  0.]
 [ 0. 15.  0.]
 [ 0.  0.  3.]]


In [8]:
R = numpy.dot(D,C)
print("R:")
print(R)

R:
[[ 9. 48. 15.]
 [ 0. 15. -9.]
 [ 0.  0.  3.]]


In [9]:
Q = numpy.array([[q1[0,0],q2[0,0],q3[0,0]],[q1[1,0],q2[1,0],q3[1,0]],[q1[2,0],q2[2,0],q3[2,0]]])
print("Q:")
print(Q)

Q:
[[ 0.33333333 -0.13333333  0.93333333]
 [ 0.66666667  0.73333333 -0.02666667]
 [ 0.66666667 -0.66666667 -0.33333333]]


In [10]:
AYY = numpy.dot(Q,R)
print("AYY:")
print(AYY)

AYY:
[[ 3.   14.    9.  ]
 [ 6.   43.    3.32]
 [ 6.   22.   15.  ]]


In [14]:
Q_ = numpy.linalg.inv(Q)
print(Q_)
print(numpy.dot(Q_, Q))
y = numpy.dot(Q_, b)
print("y:")
print(y)

[[ 0.26600541  0.67628494  0.69071235]
 [-0.20739405  0.74391344 -0.64021641]
 [ 0.94679892 -0.13525699 -0.33814247]]
[[ 1.00000000e+00 -1.14459422e-17  4.97881801e-17]
 [ 2.36927667e-17  1.00000000e+00 -1.18463833e-17]
 [-5.98993186e-18  5.98993186e-18  1.00000000e+00]]
y:
[[ 29.35076646]
 [-57.7141569 ]
 [  9.12984671]]


In [15]:
R_ = numpy.linalg.inv(R)
print(R_)
print(numpy.dot(R_, R))
x = numpy.dot(R_, y)
print("x:")
print(x)

[[ 0.11111111 -0.35555556 -1.62222222]
 [ 0.          0.06666667  0.2       ]
 [ 0.          0.          0.33333333]]
[[ 1.00000000e+00 -8.88178420e-16 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
x:
[[ 8.97114518]
 [-2.02164112]
 [ 3.04328224]]


In [17]:
print("b:")
print(numpy.dot(Q,y))

b:
[[ 26.]
 [-23.]
 [ 55.]]


In [18]:
print("y:")
print(numpy.dot(R,x))

y:
[[ 29.35076646]
 [-57.7141569 ]
 [  9.12984671]]


In [20]:
print("b:")
print(numpy.dot(A,x))

b:
[[ 26.        ]
 [-23.97385032]
 [ 55.        ]]
