In [2]:
import numpy

In [3]:
#输入一个矩阵(3阶)
A = numpy.array([[0, 4, 1],[1, 1, 1],[0, 3, 2]])
print(A)

[[0 4 1]
 [1 1 1]
 [0 3 2]]


In [4]:
a1 = numpy.array([[A[0,0]],[A[1,0]],[A[2,0]]])
print("a1")
print(a1)

a2 = numpy.array([[A[0,1]],[A[1,1]],[A[2,1]]])
print("a2")
print(a2)

a3 = numpy.array([[A[0,2]],[A[1,2]],[A[2,2]]])
print("a3")
print(a3)

a1
[[0]
 [1]
 [0]]
a2
[[4]
 [1]
 [3]]
a3
[[1]
 [1]
 [2]]


In [5]:
#正交化
b1 = a1
print("b1:")
print(b1)

k21 = (a2[0,0]*b1[0,0]+a2[1,0]*b1[1,0]+a2[2,0]*b1[2,0])/(b1[0,0]*b1[0,0]+b1[1,0]*b1[1,0]+b1[2,0]*b1[2,0])
print("k21:")
print(k21)
b2 = a2 - k21*b1
print("b2:")
print(b2)

k32 = (a3[0,0]*b2[0,0]+a3[1,0]*b2[1,0]+a3[2,0]*b2[2,0])/(b2[0,0]*b2[0,0]+b2[1,0]*b2[1,0]+b2[2,0]*b2[2,0])
print("k32:")
print(k32)
k31 = (a3[0,0]*b1[0,0]+a3[1,0]*b1[1,0]+a3[2,0]*b1[2,0])/(b1[0,0]*b1[0,0]+b1[1,0]*b1[1,0]+b1[2,0]*b1[2,0])
print("k31:")
print(k31)
b3 = a3 - k32*b2 - k31*b1
print("b3:")
print(b3)


b1:
[[0]
 [1]
 [0]]
k21:
1.0
b2:
[[4.]
 [0.]
 [3.]]
k32:
0.4
k31:
1.0
b3:
[[-0.6]
 [ 0. ]
 [ 0.8]]


In [6]:
b1m = numpy.sqrt((b1**2).sum())
q1 = numpy.array([[b1[0,0]/b1m],[b1[1,0]/b1m],[b1[2,0]/b1m]])
print("q1")
print(q1)

b2m = numpy.sqrt((b2**2).sum())
q2 = numpy.array([[b2[0,0]/b2m],[b2[1,0]/b2m],[b2[2,0]/b2m]])
print("q2")
print(q2)

b3m = numpy.sqrt((b3**2).sum())
q3= numpy.array([[b3[0,0]/b3m],[b3[1,0]/b2m],[b3[2,0]/b3m]])
print("q3")
print(q3)


q1
[[0.]
 [1.]
 [0.]]
q2
[[0.8]
 [0. ]
 [0.6]]
q3
[[-0.6]
 [ 0. ]
 [ 0.8]]


In [7]:
C = numpy.array([[1, k21, k31],[0, 1, k32],[0, 0, 1]])
print("C:")
print(C)

C:
[[1.  1.  1. ]
 [0.  1.  0.4]
 [0.  0.  1. ]]


In [8]:
D = numpy.array([[b1m, 0, 0],[0, b2m, 0],[0, 0, b3m]])
print("D:")
print(D)

D:
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 1.]]


In [9]:
R = numpy.dot(D,C)
print("R:")
print(R)

R:
[[1. 1. 1.]
 [0. 5. 2.]
 [0. 0. 1.]]


In [10]:
Q = numpy.array([[q1[0,0],q2[0,0],q3[0,0]],[q1[1,0],q2[1,0],q3[1,0]],[q1[2,0],q2[2,0],q3[2,0]]])
print("Q:")
print(Q)

Q:
[[ 0.   0.8 -0.6]
 [ 1.   0.   0. ]
 [ 0.   0.6  0.8]]


In [11]:
AYY = numpy.dot(Q,R)
print("AYY:")
print(AYY)

AYY:
[[0. 4. 1.]
 [1. 1. 1.]
 [0. 3. 2.]]
